<?php

/**
 * Implements hook_ctools_plugin_directory() to let the system know
 * where our task plugins are.
 */
function taxonomy_panels_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'page_manager' && $plugin_type == 'tasks') {
    return 'plugins/' . $plugin_type;
  }
  if ($owner == 'ctools' && in_array($plugin_type, array('contexts', 'arguments', 'relationships'))) {
    return 'plugins/' . $plugin_type;
  }
}